// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma 7: CLI uses this URL for migrate / introspect. Prefer DIRECT_URL (direct
  // Postgres) because transaction pooler (pgbouncer) does not support all migration
  // features. App runtime still uses DATABASE_URL (pooler) in src/db.ts.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
